up

diff --git a/Modulos/conexao b/Modulos/conexao
--- a/Modulos/conexao
+++ b/Modulos/conexao
@@ -147,7 +147,7 @@
 				acl url1 dstdomain -i 127.0.0.1
 				acl url2 dstdomain -i localhost
 				acl url3 dstdomain -i $ipdovps
-				acl url4 dstdomain -i /VPSMANAGER?
+				acl url4 dstdomain -i /?
 				acl payload url_regex -i "$var_pay"
 				acl all src 0.0.0.0/0
 
@@ -166,7 +166,7 @@
 			done
 			cat <<-EOF >>$var_sqd
 				#Nome squid
-				visible_hostname VPSMANAGER 
+				visible_hostname  
 				via off
 				forwarded_for off
 				pipeline_prefetch off
@@ -1266,14 +1266,15 @@ exit 0' >$RCLOCAL
 			sks='\033[1;31mOFF'
 		}
 		[[ $(screen -list | grep -wc 'proxy') != '0' ]] && var_sks1="\033[1;32m◉" || var_sks1="\033[1;31m○"
-		[[ $(screen -list | grep -wc 'wsproxy') != '0' ]] && var_sks2="\033[1;32m◉" || var_sks2="\033[1;31m○"
+		[[ $(screen -list | grep -wc 'ws') != '0' ]] && var_sks2="\033[1;32m◉" || var_sks2="\033[1;31m○"
 		[[ $(screen -list | grep -wc 'openpy') != '0' ]] && sksop="\033[1;32m◉" || sksop="\033[1;31m○"
 		echo ""
 		echo -e "\033[1;31m[\033[1;36m1\033[1;31m] \033[1;37m• \033[1;33mSOCKS SSH $var_sks1 \033[0m"
 		echo -e "\033[1;31m[\033[1;36m2\033[1;31m] \033[1;37m• \033[1;33mWEBSOCKET $var_sks2 \033[0m"
 		echo -e "\033[1;31m[\033[1;36m3\033[1;31m] \033[1;37m• \033[1;33mSOCKS OEPNVPN $sksop \033[0m"
 		echo -e "\033[1;31m[\033[1;36m4\033[1;31m] \033[1;37m• \033[1;33mABRIR PORTA\033[0m"
-		echo -e "\033[1;31m[\033[1;36m5\033[1;31m] \033[1;37m• \033[1;33mALTERAR STATUS\033[0m"
+		echo -e "\033[1;31m[\033[1;36m5\033[1;31m] \033[1;37m• \033[1;33mALTERAR STATUS SOCKS SSH\033[0m"
+        echo -e "\033[1;31m[\033[1;36m6\033[1;31m] \033[1;37m• \033[1;33mALTERAR STATUS WEBSOCKET\033[0m"
 		echo -e "\033[1;31m[\033[1;36m0\033[1;31m] \033[1;37m• \033[1;33mVOLTAR\033[0m"
 		echo ""
 		echo -ne "\033[1;32mOQUE DESEJA FAZER \033[1;33m?\033[1;37m "
@@ -1339,7 +1340,7 @@ exit 0' >$RCLOCAL
 				echo -e "\E[41;1;37m             WEBSOCKET              \E[0m"
 				echo ""
 				fun_wssocksoff() {
-					for pidproxy in $(screen -ls | grep ".wsproxy" | awk {'print $1'}); do
+					for pidproxy in $(screen -ls | grep ".ws" | awk {'print $1'}); do
 						screen -r -S "$pidproxy" -X quit
 					done
 					[[ $(grep -wc "wsproxy.py" /etc/autostart) != '0' ]] && {
@@ -1371,12 +1372,12 @@ exit 0' >$RCLOCAL
 				verif_ptrs $porta
 				fun_iniwssocks() {
 					sleep 1
-					screen -dmS wsproxy python /etc/VPSManager/wsproxy.py $porta
+					screen -dmS ws python /etc/VPSManager/wsproxy.py $porta
 					[[ $(grep -wc "wsproxy.py" /etc/autostart) = '0' ]] && {
-						echo -e "netstat -tlpn | grep -w $porta > /dev/null || {  screen -r -S 'wsproxy' -X quit;  screen -dmS wsproxy python /etc/VPSManager/wsproxy.py $porta; }" >>/etc/autostart
+						echo -e "netstat -tlpn | grep -w $porta > /dev/null || {  screen -r -S 'ws' -X quit;  screen -dmS ws python /etc/VPSManager/wsproxy.py $porta; }" >>/etc/autostart
 					} || {
 						sed -i '/wsproxy.py/d' /etc/autostart
-						echo -e "netstat -tlpn | grep -w $porta > /dev/null || {  screen -r -S 'wsproxy' -X quit;  screen -dmS wsproxy python /etc/VPSManager/wsproxy.py $porta; }" >>/etc/autostart
+						echo -e "netstat -tlpn | grep -w $porta > /dev/null || {  screen -r -S 'ws' -X quit;  screen -dmS ws python /etc/VPSManager/wsproxy.py $porta; }" >>/etc/autostart
 					}
 				}
 				echo ""
@@ -1384,7 +1385,7 @@ exit 0' >$RCLOCAL
 				echo ""
 				fun_bar 'fun_iniwssocks'
 				echo ""
-				echo -e "\033[1;32mWEBSOCKET ATIVADO COM SUCESSO\033[1;33m"
+				echo -e "\033[1;32mWSSOCKS ATIVADO COM SUCESSO\033[1;33m"
 				sleep 3
 				fun_socks
 			fi
@@ -1486,10 +1487,9 @@ exit 0' >$RCLOCAL
 				fun_socks
 			fi
 		elif [[ "$resposta" = '5' ]]; then
-			if ps x | grep -w proxy.py | grep -v grep 1>/dev/null 2>/dev/null; then
-				clear
+            if ps x | grep -w proxy.py | grep -v grep 1>/dev/null 2>/dev/null; then
+                clear
 				msgsocks=$(cat /etc/VPSManager/proxy.py | grep -E "MSG =" | awk -F = '{print $2}' | cut -d "'" -f 2)
-				msgsocks=$(cat /etc/VPSManager/wsproxy.py | grep -E "MSG =" | awk -F = '{print $2}' | cut -d "'" -f 2)
 				echo -e "\E[44;1;37m             PROXY SOCKS              \E[0m"
 				echo ""
 				echo -e "\033[1;33mSTATUS: \033[1;32m$msgsocks"
@@ -1501,6 +1501,11 @@ exit 0' >$RCLOCAL
 					sleep 2
 					fun_conexao
 				}
+				[[ ${msgg} != ?(+|-)+([a-zA-Z0-9-. ]) ]] && {
+					echo -e "\n\033[1;31m[\033[1;33m!\033[1;31m]\033[1;33m EVITE CARACTERES ESPECIAIS\033[0m"
+					sleep 2
+					fun_socks
+				}
 				echo -e "\n\033[1;31m[\033[1;36m01\033[1;31m]\033[1;33m AZUL"
 				echo -e "\033[1;31m[\033[1;36m02\033[1;31m]\033[1;33m VERDE"
 				echo -e "\033[1;31m[\033[1;36m03\033[1;31m]\033[1;33m VERMELHO"
@@ -1511,8 +1516,6 @@ exit 0' >$RCLOCAL
 				echo -e "\033[1;31m[\033[1;36m08\033[1;31m]\033[1;33m ROXO"
 				echo -e "\033[1;31m[\033[1;36m09\033[1;31m]\033[1;33m PRETO"
 				echo -e "\033[1;31m[\033[1;36m10\033[1;31m]\033[1;33m SEM COR"
-				echo ""
-				echo -e "\033[1;32mREINICIE SUA VPS PARA EVITAR FALHA NA CONEXÃO"
 				echo ""
 				echo -ne "\033[1;32mQUAL A COR\033[1;31m ?\033[1;37m : "
 				read sts_cor
@@ -1543,14 +1546,9 @@ exit 0' >$RCLOCAL
 				fun_msgsocks() {
 					msgsocks2=$(cat /etc/VPSManager/proxy.py | grep "MSG =" | awk -F = '{print $2}')
 					sed -i "s/$msgsocks2/ '$msgg'/g" /etc/VPSManager/proxy.py
-					msgsocks2=$(cat /etc/VPSManager/wsproxy.py | grep "MSG =" | awk -F = '{print $2}')
-					sed -i "s/$msgsocks2/ '$msgg'/g" /etc/VPSManager/wsproxy.py
 					sleep 1
 					cor_old=$(grep 'color=' /etc/VPSManager/proxy.py | cut -d '"' -f2)
 					sed -i "s/\b$cor_old\b/$cor_sts/g" /etc/VPSManager/proxy.py
-					cor_old=$(grep 'color=' /etc/VPSManager/wsproxy.py | cut -d '"' -f2)
-					sed -i "s/\b$cor_old\b/$cor_sts/g" /etc/VPSManager/wsproxy.py
-
 				}
 				echo ""
 				echo -e "\033[1;32mALTERANDO STATUS!"
@@ -1568,26 +1566,105 @@ exit 0' >$RCLOCAL
 						screen -dmS proxy python /etc/VPSManager/proxy.py $_Ptsks
 						rm /tmp/Pt_sks
 					fi
-				}
-				restartwssocks() {
-					if ps x | grep wsproxy.py | grep -v grep 1>/dev/null 2>/dev/null; then
-						echo -e "$(netstat -nplt | grep 'python' | awk {'print $4'} | cut -d: -f2 | xargs)" >/tmp/Pt_sks
-						for pidwsproxy in $(screen -ls | grep ".proxy" | awk {'print $1'}); do
-							screen -r -S "$pidwsproxy" -X quit
-						done
-						screen -wipe >/dev/null
-						_Ptsks="$(cat /tmp/Pt_sks)"
-						sleep 1
-						screen -dmS proxy python /etc/VPSManager/wsproxy.py $_Ptsks
-						rm /tmp/Pt_sks
-					fi
-				}
+                }
 				echo ""
 				echo -e "\033[1;32mREINICIANDO PROXY SOCKS!"
 				echo ""
 				fun_bar 'restartsocks'
 				echo ""
-                echo -e "\033[1;32mREINICIANDO WEBSOCKET!"
+				echo -e "\033[1;32mSTATUS ALTERADO COM SUCESSO!"
+				sleep 2
+				fun_socks
+			else
+				clear
+				echo -e "\033[1;31mFUNCAO INDISPONIVEL\n\n\033[1;33mATIVE O SOCKS SSH PRIMEIRO !\033[1;33m"
+				sleep 2
+				fun_socks
+			fi
+        elif [[ "$resposta" = '6' ]]; then
+            if ps x | grep -w wsproxy.py | grep -v grep 1>/dev/null 2>/dev/null; then
+                clear
+				msgsocks=$(cat /etc/VPSManager/wsproxy.py | grep -E "MSG =" | awk -F = '{print $2}' | cut -d "'" -f 2)
+				echo -e "\E[44;1;37m             WEBSOCKET              \E[0m"
+				echo ""
+				echo -e "\033[1;33mSTATUS: \033[1;32m$msgsocks"
+				echo""
+				echo -ne "\033[1;32mINFORME SEU STATUS\033[1;31m:\033[1;37m "
+				read msgg
+				[[ -z "$msgg" ]] && {
+					echo -e "\n\033[1;31mStatus invalido!"
+					sleep 2
+					fun_conexao
+				}
+				[[ ${msgg} != ?(+|-)+([a-zA-Z0-9-. ]) ]] && {
+					echo -e "\n\033[1;31m[\033[1;33m!\033[1;31m]\033[1;33m EVITE CARACTERES ESPECIAIS\033[0m"
+					sleep 2
+					fun_socks
+				}
+				echo -e "\n\033[1;31m[\033[1;36m01\033[1;31m]\033[1;33m AZUL"
+				echo -e "\033[1;31m[\033[1;36m02\033[1;31m]\033[1;33m VERDE"
+				echo -e "\033[1;31m[\033[1;36m03\033[1;31m]\033[1;33m VERMELHO"
+				echo -e "\033[1;31m[\033[1;36m04\033[1;31m]\033[1;33m AMARELO"
+				echo -e "\033[1;31m[\033[1;36m05\033[1;31m]\033[1;33m ROSA"
+				echo -e "\033[1;31m[\033[1;36m06\033[1;31m]\033[1;33m CYANO"
+				echo -e "\033[1;31m[\033[1;36m07\033[1;31m]\033[1;33m LARANJA"
+				echo -e "\033[1;31m[\033[1;36m08\033[1;31m]\033[1;33m ROXO"
+				echo -e "\033[1;31m[\033[1;36m09\033[1;31m]\033[1;33m PRETO"
+				echo -e "\033[1;31m[\033[1;36m10\033[1;31m]\033[1;33m SEM COR"
+				echo ""
+				echo -ne "\033[1;32mQUAL A COR\033[1;31m ?\033[1;37m : "
+				read sts_cor
+				if [[ "$sts_cor" = "1" ]] || [[ "$sts_cor" = "01" ]]; then
+					cor_sts='blue'
+				elif [[ "$sts_cor" = "2" ]] || [[ "$sts_cor" = "02" ]]; then
+					cor_sts='green'
+				elif [[ "$sts_cor" = "3" ]] || [[ "$sts_cor" = "03" ]]; then
+					cor_sts='red'
+				elif [[ "$sts_cor" = "4" ]] || [[ "$sts_cor" = "04" ]]; then
+					cor_sts='yellow'
+				elif [[ "$sts_cor" = "5" ]] || [[ "$sts_cor" = "05" ]]; then
+					cor_sts='#F535AA'
+				elif [[ "$sts_cor" = "6" ]] || [[ "$sts_cor" = "06" ]]; then
+					cor_sts='cyan'
+				elif [[ "$sts_cor" = "7" ]] || [[ "$sts_cor" = "07" ]]; then
+					cor_sts='#FF7F00'
+				elif [[ "$sts_cor" = "8" ]] || [[ "$sts_cor" = "08" ]]; then
+					cor_sts='#9932CD'
+				elif [[ "$sts_cor" = "9" ]] || [[ "$sts_cor" = "09" ]]; then
+					cor_sts='black'
+				elif [[ "$sts_cor" = "10" ]]; then
+					cor_sts='null'
+				else
+					echo -e "\n\033[1;33mOPCAO INVALIDA !"
+					cor_sts='null'
+				fi
+				fun_msgsocks() {
+                    msgwssocks2=$(cat /etc/VPSManager/wsproxy.py | grep "MSG =" | awk -F = '{print $2}')
+					sed -i "s/$msgwssocks2/ '$msgg'/g" /etc/VPSManager/wsproxy.py
+					sleep 1
+					cor_old=$(grep 'color=' /etc/VPSManager/wsproxy.py | cut -d '"' -f2)
+					sed -i "s/\b$cor_old\b/$cor_sts/g" /etc/VPSManager/wsproxy.py
+
+				}
+				echo ""
+				echo -e "\033[1;32mALTERANDO STATUS!"
+				echo ""
+				fun_bar 'fun_msgsocks'
+                restartwssocks() {
+                    if ps x | grep wsproxy.py | grep -v grep 1>/dev/null 2>/dev/null; then
+						echo -e "$(netstat -nplt | grep 'python' | awk {'print $4'} | cut -d: -f2 | xargs)" >/tmp/Pt_wssks
+						for pidproxy in $(screen -ls | grep ".ws" | awk {'print $1'}); do
+							screen -r -S "$pidproxy" -X quit
+						done
+						screen -wipe >/dev/null
+						_Ptwssks="$(cat /tmp/Pt_wssks)"
+						sleep 1
+						screen -dmS ws python /etc/VPSManager/wsproxy.py $_Ptwssks
+						rm /tmp/Pt_wssks
+					fi
+				}
+				echo ""
+				echo -e "\033[1;32mREINICIANDO WEBSOCKET!"
 				echo ""
 				fun_bar 'restartwssocks'
 				echo ""
@@ -1596,7 +1673,7 @@ exit 0' >$RCLOCAL
 				fun_socks
 			else
 				clear
-				echo -e "\033[1;31mFUNCAO INDISPONIVEL\n\n\033[1;33mATIVE O SOCKS SSH PRIMEIRO !\033[1;33m"
+				echo -e "\033[1;31mFUNCAO INDISPONIVEL\n\n\033[1;33mATIVE O WEBSOCKET PRIMEIRO !\033[1;33m"
 				sleep 2
 				fun_socks
 			fi
